# Generated by Django 5.0.2 on 2024-03-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('cpassword', models.CharField(max_length=40)),
                ('city', models.BigIntegerField()),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
