# Generated by Django 5.0.2 on 2024-03-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='city',
            field=models.CharField(max_length=40),
        ),
    ]
