# Generated by Django 5.0.2 on 2024-03-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tms', '0002_alter_reg_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='god',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('a_mobile', models.BigIntegerField()),
                ('truck_type', models.CharField(max_length=40)),
                ('p_city', models.CharField(max_length=40)),
                ('d_city', models.CharField(max_length=40)),
                ('goods', models.CharField(max_length=400)),
            ],
        ),
    ]
