# Generated by Django 5.0.2 on 2024-03-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tms', '0006_reg_gender_reg_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='god',
            name='a_mobile',
        ),
        migrations.AddField(
            model_name='god',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
